# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ main ]    
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_PWD }}
         
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
         context: ./src
         file: ./src/Dockerfile
         push: true
         tags: |
            erecnovais/rotten-potatos:latest
            erecnovais/rotten-potatos:${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
              metod: kubeconfig
              kubeconfig: ${{ secrets.KUBECONFIG }}
          
